### PR TITLE
TST 0.0.2 will not run without TMP and a prefs insert in PM 28.0.0b2

### PR DESCRIPTION
**Pull request by thehandyman1957**
Short description

Tree Style Tabs will not work at all without installing TMP (almost any version from 0.5.0.4 down.
If I install TMP tabs only show on the left side of the browser. If I choose the right side in settings, nothing changes until the browser is restarted and then all tab windows are greyed out. At this point the profile has to be reset because you can't even see the add on page to uninstall or disable.
So then if I install again in the same order, but don't change the right side in settings, close the browser and then open the "prefs" file in the profile and insert this line: "user_pref("browser.tabs.animate", false);" restart the browser and it will then work and you can change preferences at this point.
Steps to reproduce

    New Profile, Install TST and restart. Tabs still on top, settings won't change anything.
    Install TMP and upon restart, tabs will be on the left. Changing the settings for tabs on the right will not change anything until a browser restart. At this point the browser screen is grey and you can't see anything except the tabs.
    Delete profile to start over. Install TST and restart. Install TMP and restart. Do not change any of the TST settings. Close the browser.
    Open the "prefs" file in the profile and insert this line: "user_pref("browser.tabs.animate", false);" and save and start browser. Now all settings work and you can change the tabs to the right hand side.

Expected result

Install TST and it works out of box.
Actual result

As stated above, you must install TMP (version does not matter) and then change the prefs file.
Environment

    Platform (OS): Windows 7 Pro 64 bit
    Version of Pale Moon: Pale Moon 28.0.0b1 64bit
    Version (or revision) of Tree Style Tab: 0.0.2

### CODE REVIEW

**Comment by piroor** [comment]
I think you should create a pull request for the forked version instead of this original version.

**Comment by thehandyman1957** [comment]
Yup, I did.  Thanks.

**Comment by thehandyman1957** [comment]
There seems to be a glitch in the Matrix.  I made my pull request on oinkin/treestyletab forked from piroor/treestyletab  But when I click on the "new pull request" it sends me to piroor/treestyletab
instead.  Thus now, I understand your comment that I responded to thinking I had made the pull request to the forked author.
screenshot - 7_9_2018 7_40_23 am

Does anyone know how to get the pull request to work for the right author?  
Or is there another place to find this?

**Comment by piroor** [comment]
This is interesting. Hmm...

When I create a pull request, I usually do:

 1. Fork the original repository to my account.
 2. Clone the forked repository to the local.
 3. Commit changes to the local repository.
 4. Push changes to the forked repository under my account.
 5. Go to the top page of the forked repository under my account.
 6. Then there is a button to create a pull request from pushed changes. I just click the button and I create a pull request.

I've never tried the "New pull request" button in the pull requests page.

**Pull request closed without merging**
