### PR TITLE
[API Improvement] Allow preventing middle click to close tab 

### LINKED ISSUE #1861: [API Improvement] Allow preventing middle click to close tab
## Short description
Before Firefox 57 I was using Tree Style Tab together with [Auto Unload Tab by def00111](https://addons.mozilla.org/firefox/addon/auto-unload-tab/). I configured Auto unload tab to unload tabs when they were middle clicked, so tabs were only closed on middle click if they were already unloaded. I tried to replicate this behavior with my extension [Tab Unloader for Tree Style Tab by Lej77](https://addons.mozilla.org/firefox/addon/tab-unload-for-tree-style-tab/). Unfortunately I can't prevent Tree Style Tab from closing a tab when it is middle clicked. It would be nice if this could be implemented.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install [Tab Unloader for Tree Style Tab by Lej77](https://addons.mozilla.org/firefox/addon/tab-unload-for-tree-style-tab/).
 4. Middle click a loaded tab.

## Expected result
The tab should be unloaded but remain open.

## Actual result
The tab is closed.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: Firefox 59.0.2
 * Version (or revision) of Tree Style Tab: 2.4.18

### PR DESCRIPTION
**Pull request by Lej77**
Allow preventing middle click to close tab by sending true when listening to `mouse-up` TST API event.
This will fix #1861.

### CODE REVIEW

**Comment by piroor** [comment]
I think only the "detection of canceled" state should be exposed instead of the raw responses of `tab-mouseup` message. The commit 58df17336e16f175dedee73685b0e9e9feeb4e36 should cover this PR, thus I close this. Anyway, thank you for the advice!

**Comment by Lej77** [comment]
@piroor Your code always uses `await` on the results which means that functionality that shouldn't be affected by that wait is. Just imagine if there is an infinite wait at that point. What functionality could that break? My implementation only waited on the results just before closing the tabs and the `onMouseUp` function could continue to execute its code even when we are waiting for the results.

**Comment by piroor** [comment]
Thanks! I missed the viewpoint... By the commit 413a614 TST doesn't wait responses from other extensions until the information is really required.

**Comment by Lej77** [comment]
You new commit seems fine. 

At first I thought that a delayed API promise could cause a API message for `kTSTAPI_NOTIFY_TABBAR_MOUSEUP` to be sent long after a click happened but after looking some more I realized that `promisedCanceled` will only be a promise set by the API if the `tab` variable is true and under those circumstances the code on lines 381-395 won't be triggered. This might be clearer if the `!(await promisedCanceled)` on line 354 is changed to `!tab || !(await promisedCanceled).

**Comment by piroor** [comment]
By recent commits, now the function `onMouseUp` is rewritten to early-return style, so I think it became more readable now.

**Comment by Lej77** [comment]
Yes, that is a lot better!

**Pull request closed without merging**
