### PR TITLE
small fixes to High Contrast theme

### PR DESCRIPTION
**Pull request by actionless**
fix(themes: highcontrast): fix throbber in normal tab, closebutton in focused tab, border color in newtab-button and add fix for mac os

now only screenshot remains

### CODE REVIEW

**Comment by actionless** [comment]
2017-12-03--1512324486_1102x731_scrot

**Comment by piroor** [comment]
Sorry, my recent changes break your PR... Could you update your patch?

**Comment by actionless** [comment]
done

**Comment by piroor** [comment]
Thanks!

**Comment by piroor** [comment]
Finally I think this theme has become good another choice for people who want more accessibility. Thanks again.

**Pull request merged**
