### PR TITLE
Add 'System Colors' theme

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by piroor** [comment]
To fix the issue #1641 I've introduced some changes to apply system colors only on Linux. So I think there is less reason to add new theme for system colors. How do you think? You'll try the fix on the latest development (unsigned) build: https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi

**Comment by actionless** [comment]
i've tried your build -- system colorscheme is fixed there.
However on dark colorscheme hover tab style is not clearly distinguishable from a normal tab style. What do you think about renaming the theme in PR from 'System Colors' to 'High Contrast'?

Also i've noticed a (probably unrelated) bug what colortheme is being applied only after browser restart.

**Comment by piroor** [comment]
Hmm, ”High Contrast" seems not appropriate name on some environment. On my Windows 10, the background color of the tab bar is similar to the color of tabs.
image

**Comment by piroor** [comment]
> Also i've noticed a (probably unrelated) bug what colortheme is being applied only after browser restart.

Sorry, fdb372e should fix it.

**Comment by actionless** [comment]
> Sorry, fdb372e should fix it.
Thanks! I've rebuilt the extension and now it's fine.

I also tried to make few screenshots with dark and light system themes with "Flat" TST theme and the one from PR:

flat-light  sc-light


flat-dark sc-dark


mb show theme only if platform is Linux?

**Comment by piroor** [comment]
Hmm, interesting. on my environment (Windows 10) `ThreeDShadow` is enough darker than `ThreeDFace`. and `InactiveBorder` is not. Opposite, `ThreeDShadow` is not enough different and `InactiveBorder` is different from `ThreeDFace`  on your environment.

**Comment by piroor** [comment]
How about `ThreeDDarkShadow` in your environment? I think it should enough different from `ThreeDFace`.

**Comment by actionless** [comment]
with all system themes i've tried that color was just black, btw i am using this page as test:

http://www.iangraham.org/books/xhtml1/appd/update-23feb2000.html

**Comment by actionless** [comment]
I also added one more commit which adds the missing tab borders to this theme.

**Comment by actionless** [comment]
thanks for merging, i'll try to support it if it will require changes on browser updates

**Comment by piroor** [comment]
Oops its my mistake, I just thought to try it on  different branch...

**Comment by piroor** [comment]
Currently still I think this theme is not ready to merge,  because I still need more reasons: why it is better than existing one? user-defined styles doesn't solve it? And it also need more fixes: missing throbber on my environment, missing thumbnail, mismathed name (it should be "High Contrast").

**Comment by piroor** [comment]
> And it also need more fixes: missing throbber on my environment, missing thumbnail, mismathed name (it should be "High Contrast").

Could you add more PRs for them?

**Comment by actionless** [comment]
yes, i can prepare it tomorrow.

what do you think about such style for a throbber?

```css
.tab.active .throbber {
  background-color: HighlightText;
  border-radius: 6px;
}
```

**Comment by piroor** [comment]
I think you should define throbber color via css variable, instead of direct declatation. See also:
https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/metal/metal.css#L4
https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/sidebar/sidebar.css#L50
https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/sidebar/sidebar.css#L60

And please don't forget to define extra padding for overlay scrollbar on macOS.
https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/metal/metal.css#L43

Like this you need to maintain theme for platform you don't (possibly never) use also. This is the largest reason why I'm inaggressive to add new themes...

**Comment by piroor** [comment]
> Hmm, interesting. on my environment (Windows 10) ThreeDShadow is enough darker than ThreeDFace. and InactiveBorder is not. Opposite, ThreeDShadow is not enough different and InactiveBorder is different from ThreeDFace on your environment.

To solve this problem, I propose to unify color of tab bar (background area) to text color, like:

```css
root {
    background: ButtonText;
}
```

In your screenshot `ButtonText` and `InactiveBorder` seems similar. How about this?

**Comment by actionless** [comment]
`ButtonText` seems to be too much contrast, ie on light colorschemes it's usually a black color, on dark light-light-grey (almost white)

**Comment by piroor** [comment]
By 59dc58e537311b4444d984ad3761dcf009b67ab5 I've introduced new element just for background. It is independent from the tab bar, so you can set both system color background and opacity for it. The current color (65% `ButtonFace` + 35% `ButtonText`) is just an example. Could you create PR to change this to fit your environment? If the color have enough high contrast on my environment also, I'll ship it as a part of next release.

**Pull request merged**
