### PR TITLE
Add defer attribute to script elements

### PR DESCRIPTION
**Pull request by saneyuki**
## Motivation

`script[type="module"]` will be executed on when parsing html document is complete. This behavior is a similar to the one of `script[defer]`.

This means that `script[defer]` decreases a complexity to migrate to a module script from a classic script.

## See also

- [4.12.1 The script element - WHATWG HTML Standard](https://html.spec.whatwg.org/multipage/scripting.html#the-script-element)

### CODE REVIEW

**Comment by saneyuki** [comment]
@piroor how about do you think?

**Comment by piroor** [comment]
Sadly this change reintroduces the problem reported at #1714. Do you have any good idea to  solve both?

**Comment by saneyuki** [comment]
@piroor 

I'm not sure about the root problem with #1714. I suspect that scripts will not block to parse a document and sets the style just before `DOMContentLoaded`. Even if we switch to a module script, #1714 would be reproducible.

I feel it may fix to apply dark background color to body or document style because user attention will focus to a white color.

**Comment by saneyuki** [comment]
@piroor 

I rebased this pull request on the tip of `master` branch.
And I had tried whether this change still causes the regression about #1714, but I didn't reproduce it by the rebased this branch. Perhaps my reproduce steps was wrong.

How do you feeling about this?

**Comment by piroor** [comment]
Hmm, the regression I worried seems not happen for me also. And I misunderstood that `defer` as `async`. I've decided to merge this and try further more doogfooding.

**Comment by piroor** [comment]
Anyway, thanks!

**Pull request merged**
